accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('profile/<username>', views.ProfileView.as_view(), name='profile'),
    path('myDetail/<pk>/', views.myDetail.as_view(), name="myDetail"),
]

blog/urls.py
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.Index.as_view(), name="blog"),
    path('detail/<pk>/', views.Detail.as_view(), name="detail"),
    path('create/', views.Create.as_view(), name="create"),
    path('delete/<pk>', views.Delete.as_view(), name="delete"),
]

term_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("wake_up.urls")),
    path('blog/', include("blog.urls")),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

wake_up/urls.py
from django.urls import path, include

from .views import IndexView, VideoView

from . import views

urlpatterns = [
    path('', IndexView.as_view()),
    path('video', VideoView.as_view()),
    path('video_feed', views.video_feed_view(), name="video_feed"),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth import get_user, get_user_model
from django.urls import reverse_lazy

# class Category(models.Model):
#     name = models.CharField(
#         max_length=255,
#         blank=False,
#         null=False,
#         unique=True)
    
#     def __str__(self):
#         return self.name
    
# class Tag(models.Model):
#     name = models.CharField(
#         max_length=255,
#         blank=False,
#         null=False,
#         unique=True)
    
#     def __str__(self):
#         return self.name

User = get_user_model()

class Post(models.Model):
    created = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        blank=False,
        null=False)
    
    updated = models.DateTimeField(
        auto_now=True,
        editable=False,
        blank=False,
        null=False)
        
    title = models.CharField(
        max_length=255,
        blank=False,
        null=False)
        
    body = models.TextField(
        blank=True,
        null=False)
    
    user = models.ForeignKey(
        User, 
        on_delete=models.CASCADE)

    # author = models.ForeignKey(
    #     get_user_model(),
    #     on_delete=models.CASCADE,
    # )
    # category = models.ForeignKey(
    #     Category,
    #     on_delete=models.CASCADE)

    # tags = models.ManyToManyField(
    #     Tag,
    #     blank=True)
    
    def get_absolute_url(self):
        return reverse_lazy("detail", args=[self.id])

    def __str__(self):
        return self.title

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import TemplateView
from django.views.generic import ListView, DetailView

from blog.models import Post


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

class ProfileView(ListView):
    template_name = 'accounts/profiel.html'
    model = Post

class myDetail(DetailView):
    # 詳細表示するモデルを指定 -> `object`で取得可能
    template_name = 'accounts/myPost_detail.html'
    model = Post

blog/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView

from .models import Post

class Index(ListView):
    # 一覧するモデルを指定 -> `object_list`で取得可能
    model = Post

class Detail(DetailView):
    # 詳細表示するモデルを指定 -> `object`で取得可能
    model = Post

# CreateViewは新規作成画面を簡単に作るためのView
class Create(CreateView):
    model = Post
    
    # 編集対象にするフィールド
    fields = ["title", "body"]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class Delete(DeleteView):
    model = Post
    
    # 削除したあとに移動する先（トップページ）
    success_url = "/blog"

wake_up/views.py
from urllib import request
from django.views.generic import TemplateView

class IndexView(TemplateView):
    template_name = "index.html"

#------------------video---------

import cv2
from django.http import StreamingHttpResponse
from django.shortcuts import render
from django.views import View
import time
import cv2
import dlib
from imutils import face_utils
from scipy.spatial import distance
from playsound import playsound

# ストリーミング画像・映像を表示するview
class VideoView(View):
    def get(self, request):
        return render(request, 'video.html', {})

# ストリーミング画像を定期的に返却するview
def video_feed_view():
    return lambda _: StreamingHttpResponse(generate_frame(), content_type='multipart/x-mixed-replace; boundary=frame')

# フレーム生成・返却する処理
Xml_path = "C:/tutorial/Mypython/termproject/haarcascade_frontalface_alt2.xml"
Dat_path = "C:/tutorial/Mypython/termproject/shape_predictor_68_face_landmarks.dat"

<<<<<<< HEAD
""" Xml_path = "/Volumes/USB DISK/iwai_lab/term_project/wake_up/material/haarcascade_frontalface_alt2.xml"
Dat_path = "/Volumes/USB DISK/iwai_lab/term_project/wake_up/material/shape_predictor_68_face_landmarks.dat" """
Sound_path = "C:/tutorial/Mypython/term_project_3/term_project/wake_up/material/soundb.wav"
=======
Xml_path = "/Volumes/USB DISK/iwai_lab/term_project/wake_up/material/haarcascade_frontalface_alt2.xml"
Dat_path = "/Volumes/USB DISK/iwai_lab/term_project/wake_up/material/shape_predictor_68_face_landmarks.dat"
Sound_path = "/Volumes/USB DISK/iwai_lab/term_project/wake_up/material/soundb.wav"
>>>>>>> 0f91716d2a917c872bc257f77603a47bdac0faeb


def generate_frame():
    face_1 = cv2.CascadeClassifier(Xml_path)
    face_parts_1 = dlib.shape_predictor(Dat_path)
    t1 = 0.0
    close_eye = 0.0
    
    capture = cv2.VideoCapture(0)  # USBカメラから
    
    while True:
        if not capture.isOpened():
            print("Capture is not opened.")
            break
        # カメラからフレーム画像を取得
        ret, frame = capture.read()
        if not ret:
            print("Failed to read frame.")
            break
        
        gray = cv2.cvtColor(frame,cv2.COLOR_RGB2GRAY)
        faces = face_1.detectMultiScale(gray, scaleFactor=1.11, minNeighbors=3, minSize=(100, 100))

        if len(faces) == 1:
            x,y,w,h = faces[0]
            cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 2)
            
            face_gray = gray[y :(y + h), x :(x + w)]
            scale = 480 / h
            face_gray_resized = cv2.resize(face_gray, dsize=None, fx=scale, fy=scale)
            face = dlib.rectangle(0, 0, face_gray_resized.shape[1], face_gray_resized.shape[0])
            face_parts = face_parts_1(face_gray_resized, face)
            face_parts = face_utils.shape_to_np(face_parts)
            
            left = face_parts[42:48]
            left_ear = calc_ear(left)
            
            right = face_parts[36:42]
            right_ear = calc_ear(right)
            
            if (left_ear + right_ear) < 0.55:
                if t1 == 0.0:
                    t1 = time.time()
                else:
                    close_eye += time.time()-t1
                    t1 = time.time()
                cv2.putText(frame,str(round(close_eye)), (10,40), cv2.FONT_HERSHEY_PLAIN, 3, (0,0,255), 3, 1)  
                if close_eye > 3.0:
                    cv2.putText(frame,"Sleepy eyes. Wake up!", (10,80), cv2.FONT_HERSHEY_PLAIN, 2, (0,0,255), 3, 1)
                    playsound(Sound_path) 
            else:
                close_eye = 0.0
                t1 = 0.0

        # フレーム画像バイナリに変換
        ret, jpeg = cv2.imencode('.jpg', frame)
        byte_frame = jpeg.tobytes()
        # フレーム画像のバイナリデータをユーザーに送付する
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + byte_frame + b'\r\n\r\n')
    capture.release()

def calc_ear(eye):
    A = distance.euclidean(eye[1], eye[5])
    B = distance.euclidean(eye[2], eye[4])
    C = distance.euclidean(eye[0], eye[3])
    eye_ear = (A + B) / (2.0 * C)
    return round(eye_ear, 3)

##------------video finish

accounts/templates/accounts/myPost.html
<!-- {% extends "profile.html" %}
{% block list %}
<ol>
    <p></p>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for post in object_list %}
            {% if user == post.user %}
            <div class="col">
                <div class="card">
                    <h5 class="card-header text-white bg-secondary">{{ post.title }} :</h5>
                    <div class="card-body bg-light">
                        <p class="card-text">{{post.body}}</p>
                        <div class="btn_justify">
                            <a href="{% url 'detail' post.id %}" class="btn btn-primary btn_justify">投稿を見る　≫</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>

    <div class="row row-cols-1 row-cols-md-3 g-4">
    </div>

</ol>

<style>
    .h1_justify{
        text-align: center;
    }
    .btn_justify{
        text-align: right;
    }
    .card_justify{
        margin-bottom:50px;
    }
    .button_justify1{
        background-color:rgb(66, 112, 248);
        margin-top:10px;
        margin-bottom:10px;
        font-size: 20px;
        width: 8rem;
        height: 3rem;
        border-radius: 0.5em;
    }
</style>
{% endblock %} -->

accounts/templates/accounts/myPost_detail.html
{% extends "layout.html" %}
{% load l10n %}
{% block content %}

<div class="col-sm-6 h1_justify mx-auto">
    <div class="card">
        <h4 class="card-header text-white bg-secondary">{{ object.title }}</h4>
        <div class="card-body bg-light">
            <div class="btn_justify">
                <p>{{ object.user }}</p>
                <p style="opacity: 0.5;"><time>{{ object.updated|localize }}</time></p>
            </div>
            <div class="radius-sample1">
                <h5 style="text-align: left;">内容 :</h5>
                <u>{{ object.body }}</u>
            </div>
            <div class="btn_justify">
                <a href="{% url 'accounts:profile' post.user %}" class="btn btn-primary">戻る</a>
                {% if user == object.user %}
                <a href="{% url 'delete' post.id %}" class="btn btn-danger">削除</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<style>
    .radius-sample1{
        background-color: rgb(211, 211, 211);
        border-radius:10px 10px 10px 10px;
        width:cover;
        height:cover;
        padding: 15px;
        border:#333333 solid 2px; 
        margin-bottom:50px;
    }
    .h1_justify{
        text-align: center;
    }
    .btn_justify{
        text-align: right;
    }
    .button_justify1{
        background-color:rgb(66, 112, 248);
        margin-top:10px;
        margin-bottom:10px;
        font-size: 20px;
        width: 8rem;
        height: 3rem;
        border-radius: 0.5em;
    }
</style>

{% endblock %}

accounts/templates/accounts/profiel.html
{% extends "layout.html" %}

{% block content %}
<h1>{{ user.username }}'s Post</h1>
<div>
    <ol>
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for post in object_list %}
                {% if user == post.user %}
                <div class="col">
                    <div class="card">
                        <h5 class="card-header text-white bg-secondary">{{ post.title }} :</h5>
                        <div class="card-body bg-light">
                            <p class="card-text">{{post.body|truncatechars:50}}</p>
                            <div class="btn_justify">
                                <a href="{% url 'accounts:myDetail' post.id %}" class="btn btn-primary btn_justify">投稿を見る　≫</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %}
            {% endfor %}
        </div>

        <div class="row row-cols-1 row-cols-md-3 g-4">
        </div>

    </ol>
</div>

<style>
    .h1_justify{
        text-align: center;
    }
    .btn_justify{
        text-align: right;
    }
    .card_justify{
        margin-bottom:50px;
    }
    .button_justify1{
        background-color:rgb(66, 112, 248);
        margin-top:10px;
        margin-bottom:10px;
        font-size: 20px;
        width: 8rem;
        height: 3rem;
        border-radius: 0.5em;
    }
</style>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'layout.html' %}

{% block content %}
<div class="col-sm-8 mx-auto">
    <div class="card">
        <h4 class="card-header text-white bg-secondary" style="text-align: center;">Sign up</h4>
        <div class="card-body bg-light">
            <section class='common-form'>
                <form method='post'>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div style="text-align: center;">
                        <button type='submit' class="button_justify1">Sign up</button>
                    </div>
                </form>
            </section>
        </div>
    </div>
</div>


<style>
    .h1_justify{
        text-align: center;
    }
    .button_justify1{
        background-color:rgb(66, 112, 248);
        margin-top:10px;
        margin-bottom:10px;
        font-size: 20px;
        width: 8rem;
        height: 3rem;
        border-radius: 0.5em;
    }
</style>

{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "layout.html" %}

{% block content %}
<h2>削除確認</h2>
<div class="radius-sample1">
    <p>この投稿（{{ object.title }}）を本当に削除してもよろしいですか？</p>
    <form method="post">
        {% csrf_token %}
        <a href="{% url 'blog' %}" class="btn btn-primary">戻る</a>
        <input type="submit" value="削除" class="btn btn-danger" />
    </form>
</div>

<style>
    .radius-sample1{
        background-color: rgb(248, 246, 246);
        border-radius:10px 10px 10px 10px;
        width:400px;
        height:cover;
        padding: 15px;
        border:#333333 solid 2px;
    }
</style>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "layout.html" %}
{% load l10n %}
{% block content %}

<div class="col-sm-6 h1_justify mx-auto">
    <div class="card">
        <h4 class="card-header text-white bg-secondary">{{ object.title }}</h4>
        <div class="card-body bg-light">
            <div class="btn_justify">
                <p>{{ object.user }}</p>
                <p style="opacity: 0.5;"><time>{{ object.updated|localize }}</time></p>
            </div>
            <div class="radius-sample1">
                <h5 style="text-align: left;">内容 :</h5>
                <u>{{ object.body }}</u>
            </div>
            <div class="btn_justify">
                <a href="{% url 'blog' %}" class="btn btn-primary">戻る</a>
                {% if user == object.user %}
                <a href="{% url 'delete' post.id %}" class="btn btn-danger">削除</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<style>
    .radius-sample1{
        background-color: rgb(211, 211, 211);
        border-radius:10px 10px 10px 10px;
        width:cover;
        height:cover;
        padding: 15px;
        border:#333333 solid 2px; 
        margin-bottom:50px;
    }
    .h1_justify{
        text-align: center;
    }
    .btn_justify{
        text-align: right;
    }
    .button_justify1{
        background-color:rgb(66, 112, 248);
        margin-top:10px;
        margin-bottom:10px;
        font-size: 20px;
        width: 8rem;
        height: 3rem;
        border-radius: 0.5em;
    }
</style>

{% endblock %}

blog/templates/blog/post_form.html
{% extends "layout.html" %}

{% block content %}

<div class="col-sm-6 h1_justify mx-auto">
    <div class="card">
        <h4 class="card-header text-white bg-secondary">New blog</h4>
        <div class="card-body bg-light">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type='submit' class="button_justify1">投稿</button>
            </form>
        </div>
    </div>
</div>

<style>
    .h1_justify{
        text-align: center;
    }
    .button_justify1{
        background-color:rgb(66, 112, 248);
        margin-top:10px;
        margin-bottom:10px;
        font-size: 20px;
        width: 8rem;
        height: 3rem;
        border-radius: 0.5em;
    }
</style>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "layout.html" %}
{% block content %}
<h2>勉強記録</h2>
<ol>
    <p></p>
    <a href="{% url 'create' %}" class="btn btn-secondary card_justify">新規投稿</a>
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for post in object_list %}
            <div class="col">
                <div class="card">
                    <h5 class="card-header text-white bg-secondary">{{ post.title }} :</h5>
                    <div class="card-body bg-light">
                        <p class="card-text">{{post.body |truncatechars:50 }}</p>
                        <div class="btn_justify">
                            <a href="{% url 'detail' post.id %}" class="btn btn-primary btn_justify">投稿を見る　≫</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="row row-cols-1 row-cols-md-3 g-4">
    </div>

</ol>

<style>
    .h1_justify{
        text-align: center;
    }
    .btn_justify{
        text-align: right;
    }
    .card_justify{
        margin-bottom:50px;
    }
    .button_justify1{
        background-color:rgb(66, 112, 248);
        margin-top:10px;
        margin-bottom:10px;
        font-size: 20px;
        width: 8rem;
        height: 3rem;
        border-radius: 0.5em;
    }
</style>
{% endblock %}

templates/layout.html
<!doctype HTML>
{% load static %} 
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>    
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/termproject.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.js' %}">    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js" type="text/javascript"></script>
    </head>
    <body background={% static "02-whitepaper.png" %}>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Wake Up !!!</a>
            <ul class='navbar-nav'>
                {% if user.is_authenticated %}
                    <li class='nav-time'>
                        <a href='{% url "accounts:profile" user.id %}' class='navbar-text'>{{ user }}</a>
                        <span class='navbar-text'> - </span>
                    </li>
                    <li class='nav-item'>
                        <a href='{% url "logout" %}' class='logout nav-link'>Logout</a>
                    </li>
                    <li class='nav-item'>
                        <a href='{% url "blog" %}' class='blog nav-link'>blog</a>
                    </li>
                {% else %}
                    <li class='nav-item'>
                        <a href='{% url "login" %}' class='login nav-link'>Login</a>
                    </li>
                    <li class="nav-item">
                        <a href='{% url "accounts:signup" %}' class='signup nav-link'> Sign up </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        
        <div class="container mt-4">
        {% block content %}
        {% endblock %}
        </div>
    </body>
</html>

wake_up/templates/base.html
<!doctype HTML>
{% load static %} 
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/termproject.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.js' %}">    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js" type="text/javascript"></script>
    </head>
    <body background={% static "02-whitepaper.png" %}>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Wake Up !!!</a>
            <ul class='navbar-nav'>
                {% if user.is_authenticated %}
                    <li class='nav-time'>
                        <a href='{% url "accounts:profile" user.id %}' class='navbar-text'>{{ user }}</a>
                        <span class='navbar-text'> - </span>
                    </li>
                    <li class='nav-item'>
                        <a href='{% url "logout" %}' class='logout nav-link'>Logout</a>
                    </li>
                    <li class='nav-item'>
                        <a href='{% url "blog" %}' class='blog nav-link'>blog</a>
                    </li>
                {% else %}
                    <li class='nav-item'>
                        <a href='{% url "login" %}' class='login nav-link'>Login</a>
                    </li>
                    <li class="nav-item">
                        <a href='{% url "accounts:signup" %}' class='signup nav-link'> Sign up </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        
        {% block main %}
        <p>※コンテンツがありません。</p>
        {% endblock %}
    </body>
</html>

wake_up/templates/index.html
{% extends "layout.html" %}
{% block content %}

    <div style="text-align: center;">
        <button class="button_justify" id="start_btn" onclick="location.href='/video'">Start</button>
        <button class="button_justify" id="stop_btn" onclick="location.href='/'">Stop</button>
    </div>
    <div style="text-align: center;">
        <video id="video_area" style="background-color: #000" autoplay></video> 
    </div>

<script>

    // if (typeof navigator.mediaDevices.getUserMedia !== 'function') {
    //     const err = new Error('getUserMedia()が使えないブラウザだよ');
    //     alert(`${err.name} ${err.message}`);
    //     throw err;
    // }

    // const $start = document.getElementById('start_btn');   // スタートボタン
    // const $video = document.getElementById('video_area');  // 映像表示エリア
    // const $stop = document.getElementById('stop_btn');   // ストップボタン

    // $start.addEventListener('click', () => {
    //     navigator.mediaDevices.getUserMedia({ video: true, audio: false })
    //     .then(stream => $video.srcObject = stream)
    //     .catch(err => alert(`${err.name} ${err.message}`));
    // }, false);

    // $stop.addEventListener('click', () => {
    //     const tracks = document.getElementById('video_area').srcObject.getTracks();
    //     tracks.forEach(track => {
    //     track.stop();
    //     });

    //     document.getElementById('video_area').srcObject = null;
    // }, false);

</script>
{% endblock %}

wake_up/templates/video.html
{% extends "layout.html" %}
{% load static %}


{% block content %}
<div style="text-align: center;">
    <button class="button_justify" id="start_btn" onclick="location.href='/video'">Start</button>
    <button class="button_justify" id="stop_btn" onclick="location.href='/'">Stop</button>
</div>
<div style="text-align: center;">
    <div id="image_area">
        <img src="/video_feed" />
    </div>
</div>
<script>


</script>

{% endblock %}